#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 CASLab, National Cheng Kung University
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# Run a HAL integration test using the real daemon flow.
# It starts the lv daemon in the background, waits for it to generate the config,
# and then runs the test.

# Get the executables and scripts from arguments
DAEMON_EXEC=${1:?Daemon executable (lv) not provided}
DAEMON_LUA=${2:?Daemon lua script (daemon.lua) not provided}
TEST_EXEC=${3:?Test executable not provided}

# Change to repo root
cd "$(dirname "$0")/../.."
REPO_ROOT=$(pwd)

export AGENT_SOCKET_PATH=/tmp/formosa.sock

# Cleanup existing socket and config if any
rm -f /tmp/formosa.sock
rm -f "${REPO_ROOT}/.lv-formosa-config.sh"

# Start daemon in background
echo "Starting daemon: ${DAEMON_EXEC} ${DAEMON_LUA}"
"${DAEMON_EXEC}" "${DAEMON_LUA}" &
DAEMON_PID=$!

# Cleanup on exit
cleanup() {
  echo "Cleaning up daemon (PID: ${DAEMON_PID})..."
  kill "${DAEMON_PID}" 2>/dev/null || true
  wait "${DAEMON_PID}" 2>/dev/null || true
  rm -f /tmp/formosa.sock
  rm -f "${REPO_ROOT}/.lv-formosa-config.sh"
}
trap cleanup EXIT

# Give daemon time to start and generate .lv-formosa-config.sh
MAX_RETRIES=30
COUNT=0
echo "Waiting for .lv-formosa-config.sh to be generated..."
while [ ! -f "${REPO_ROOT}/.lv-formosa-config.sh" ] && [ "${COUNT}" -lt "${MAX_RETRIES}" ]; do
  if ! kill -0 "${DAEMON_PID}" 2>/dev/null; then
    echo "Error: Daemon died unexpectedly"
    exit 1
  fi
  sleep 1
  COUNT=$((COUNT + 1))
done

if [ ! -f "${REPO_ROOT}/.lv-formosa-config.sh" ]; then
  echo "Error: .lv-formosa-config.sh not generated by daemon after ${MAX_RETRIES} seconds"
  exit 1
fi

echo "Sourcing .lv-formosa-config.sh and running test..."
# shellcheck disable=SC1091
source "${REPO_ROOT}/.lv-formosa-config.sh"

# Run the test
"${TEST_EXEC}" "${@:4}"
TEST_EXIT_CODE=$?

exit "${TEST_EXIT_CODE}"
