# SPDX-FileCopyrightText: 2026 CASLab, National Cheng Kung University
#
# SPDX-License-Identifier: Apache-2.0

add_subdirectory(atomic_ops)
add_subdirectory(divergence)
add_subdirectory(inactive_lanes)
add_subdirectory(lmem_allocate)
add_subdirectory(spirv_smoke)
add_subdirectory(kernel_clock)
add_subdirectory(oclprintf)
add_subdirectory(copy_buffer)
